#!/usr/bin/env bash
# test server to listening on port 80 of all server's active IPv4 IPs

cd /etc/nginx/sites-enabled/ || exit;                                                                                                                             
rm default;                                                                                                                                               
ln -s /etc/nginx/sites-available/default default;                                                                                                         
service nginx restart
